config/routes.rb
Rails.application.routes.draw do
  root "projects#index"
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    acts_as_paranoid
    has_many :tasks, dependent: :destroy
    accepts_nested_attributes_for :tasks
    has_one_attached :file,  dependent: :destroy
    validates :name, presence: true


end

app/models/task.rb
class Task < ApplicationRecord
    
    belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tasks = @project.tasks.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
   
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :body, :file, tasks_attributes: [:id, :description, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocoon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_attachment.html.erb
<% if project.file.attached? %>
    <div class="row">
        <% if project.file.image? %>
            <div class="message-image-container">
                <%= image_tag(project.file, class:"message-image",size:"200x200")%>
            </div>
            <% elsif project.file.video? %>
                <%= video_tag(url_for(project.file), class:"message-video", controls: "") %>
            <% elsif project.file.audio? %>
                <%= audio_tag(url_for(project.file), class:"message-audio", controls: "")%>
            <% else %>
                <%= link_to project.file.filename, url_for(project.file), class:"message-file"%>
            <% end %>
    </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <h3>Tasks</h3>
  <div>
    <%= form.fields_for :tasks do |task|%>
      <%= render "task_fields", :f => task%>
    <%end%>
    <div>
      <%= link_to_add_association "Add Task", form, :tasks %> 
    </div>
  </div>
  <br>
 <div>
    <%= form.label :title, style: "display: block"%>
    <%= form.file_field :file%>
  </div>
  ‍
  <div >
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="container">
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

   <p>
    <strong>File:</strong>
  </p>
<%= render "projects/attachment", project: project%>
</div>
</div>

app/views/projects/_task_fields.html.erb
<div class="container">
<div class="nested-fields">
   <%= f.label "Description" %>
   <%= f.text_field :description %>
  
   <%= link_to_remove_association "Delete", f %>
</div>
</div>

app/views/projects/edit.html.erb
<div class="container">
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>
<div>
  <%= link_to "Show", @project %> |
  <%= link_to "Back", projects_path %>
</div>
</div>

app/views/projects/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>
<%= link_to "New project", new_project_path %>
<hr>
<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show", project %>
    </p>
    <hr>
  <% end %>

</div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>
<h4><%= @project.name %>'s description</h4>
<% @tasks.each do |task|%>
  <li><%= task.description %></li>
<% end %>
<br>
<div>
  <%= link_to "Edit", edit_project_path(@project) %> |
  <%= link_to "Back", projects_path %>
</div>
<br>
<div>
 
 <%= button_to 'Destroy', project_path, method: :delete,
  form: {data: {turbo_confirm: 'Are you sure?'}} %>


</div>